### ISSUE TITLE
[BUG] Websocket Reconnection failed

### ISSUE THREAD

**Issue by FaSeEngineering** [androidseb25/iGotify-Notification-Assistent#109]
**Describe the bug**

I guess its **not a bug** but a misconfiguration of nginx. However, I struggle to get it working and hope that someone else had this issue as well but solved it. The overall system should be reachable using two public domains:

- gotify.***.com
- i.gotify.***.com

Therefore, I resolve the first domain to the _gotify_ container and the second one to the _igotify_ one. The initial setup of my device (iPhone 15) seems to work fine. The logs of _igotify_ show:
```log
ClientToken: C_***
DeviceToken: NTFY-DEVICE-***
GotifyUrl: https://gotify.***
Client connecting...
Done!
```
However, after some seconds the connection seems to be interrupted:

```log
Disconnection happened, type: Error
Webseocket Reconnection failed with Error. Try to reconnect in 10s.
```

I am pretty sure that my nginx configuration is missing something but I struggle to find the mistake. The config for the `i.gotify.***.com` domain looks like:

```nginx
server {
    server_name i.gotify.***.com;
    location / {
    
        # Reverse Proxy
        proxy_pass         http://127.0.0.1:8681;
        proxy_http_version 1.1;

        # Websockets Support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_connect_timeout   60s;
        proxy_send_timeout      3600s;
        proxy_read_timeout      3600s;
    }

    # SSL
    listen 443 ssl; # managed by Certbot
    ssl_certificate ***/fullchain.pem; # managed by Certbot
    ssl_certificate_key ***/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

Do you have any idea whats wrong or missing? I appreciate your ideas and suggestions.

**Comment by androidseb25** [comment]
take a look at you're servername there is the mistake you set `igotify.***` but you use `i.gotify.***`

**Comment by FaSeEngineering** [comment]
Sorry, that was my mistake by transfering the nginx configuration and changing the server name... the original config is set to `i.gotify.***.com`. I adjusted my original post.

**Comment by androidseb25** [comment]
Did you already tried the default nginx config for igotify from the readme?

```
proxy_set_header   Host $http_host;
proxy_connect_timeout   1m;
proxy_send_timeout      1m;
proxy_read_timeout      1m;

```

Did you maybe check you're ufw?
At issue #55 someone had the same problem

**Comment by FaSeEngineering** [comment]
Yes, I started with the default settings from the README but did not have any success on that. Thanks for the reference to issue #55. I investigated it and tried adding ufw rules and disable the firewall but the error message remains. When entering the containers and installing some network tools, I am able to resolve the dns names and ping the containers. Therefore, I think that communication in general should be possible.

**Comment by androidseb25** [comment]
After how many seconds the disconnect message comes? Does he try to reconnect with success message?

**Comment by androidseb25** [comment]
did you found any solution?

**Comment by FaSeEngineering** [comment]
Unfortunately, no... I run out of ideas on what else I could try.

**Comment by r4mp** [comment]
I have the same problem, but without nginx. I have found the following error in the logs. Maybe the two cases are related

`Database is created: True
Gotify - Url: http://gotify
Is Gotify - Url available: yes
SecNtfy Server - Url: https://api.secntfy.app
Is SecNtfy Server - Url available: yes
Client - Token: XXX
Client connecting...
Done!
Disconnection happened, type: Error
Webseocket Reconnection failed with Error. Try to reconnect in 10s.
Gotify - Url: http://gotify
Is Gotify - Url available: yes
SecNtfy Server - Url: https://api.secntfy.app
Is SecNtfy Server - Url available: yes
Client - Token: XXX
Client connecting...
Done!
Disconnection happened, type: Error
Webseocket Reconnection failed with Error. Try to reconnect in 10s.
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: XXX
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartWsConn(String gotifyServerUrl, String clientToken) in /src/Services/GotifySocketService.cs:line 74
   at iGotify_Notification_Assist.Services.GotifySocketService.<>c__DisplayClass9_0.<StartWsThread>b__0() in /src/Services/GotifySocketService.cs:line 47
Database is created: True`

**Comment by r4mp** [comment]
Do you have a firewall/packet filter running that is blocking the connection between the pods? I had the same problem and found out (in my case via the iptables protocol) that I had forgotten a rule

**Comment by aks-cadesign** [comment]
I apologize for my lack of understanding, but do I need to configure that if I am running gotify and igotify with this docker compose? (actually it's a stack in portainer)

I did not configure anything with other containers in the same "net" network and they can talk with each other.

```
version: '3'

services:
  gotify:
    image: gotify/server
    hostname: igotify
    container_name: gotify
    ports:
      - 8680:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS}
    volumes:
      - './gotify_data:/app/data'
    networks:
      - net
      
  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - net
    ports:
      - "8681:8080"
    volumes:
      - './gotify_api-data:/app/data'

[nginx-proxy-manager]

networks:
  net:
    external: true
```
