### ISSUE TITLE
[BUG] v1.3.1.0

### ISSUE THREAD

**Issue by Teurg** [androidseb25/iGotify-Notification-Assistent#116]
Hi! After the update the container stopped working.
There is an error in the logs (the config was not changed):

warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
Failed to determine the https port for redirect.

**Comment by nicedevil007** [comment]
Can't help here but a small feedback for "on plain install on Linux"
=> everything works as expected, updated .Net to version 9 and then run my ansible playbook for update.

**Comment by androidseb25** [comment]
> Hi! After the update the container stopped working. There is an error in the logs (the config was not changed):
> 
> warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3] Failed to determine the https port for redirect.

Are there some more logs? This is only a warning an not an error

**Comment by doopler** [comment]
i get the same error

**Comment by androidseb25** [comment]
> i get the same error

Can you give me some logs.

Without any logs I can't help you both..

**Comment by doopler** [comment]
this is what i get in container logs 

```
Client connecting...
Done!
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
```

**Comment by androidseb25** [comment]
Please try to write the ScalarUI environment variable like this

`ENABLE_SCALAR_UI: 'true'`

**Comment by Teurg** [comment]
> > Привет! После обновления контейнер перестал работать. В логах ошибка (конфиг не менялся): 
> > предупреждение: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3] Не удалось определить порт https для перенаправления.
> 
> Есть еще логи? Это всего лишь предупреждение, а не ошибка
```
Client connecting...

Done!

info: Microsoft.Hosting.Lifetime[14]

      Now listening on: http://[::]:8080

info: Microsoft.Hosting.Lifetime[0]

      Application started. Press Ctrl+C to shut down.

info: Microsoft.Hosting.Lifetime[0]

      Hosting environment: Production

info: Microsoft.Hosting.Lifetime[0]

      Content root path: /app

warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]

      Failed to determine the https port for redirect.
```
```
services:
  gotify:
    image: gotify/server
    container_name: gotify
    volumes:
      - ./gotify_data:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - TZ=Asia/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.entrypoints=http"
      - "traefik.http.routers.gotify.rule=Host(`gotify.domain.com`)"
      - "traefik.http.middlewares.gotify-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gotify.middlewares=gotify-https-redirect"
      - "traefik.http.routers.gotify-secure.entrypoints=https"
      - "traefik.http.routers.gotify-secure.rule=Host(`gotify.domain.com`)"
      - "traefik.http.routers.gotify-secure.tls=true"
      - "traefik.http.routers.gotify-secure.service=gotify"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  igotify-notification: # (iGotify-Notification-Assistent)
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./api-data:/app/data
    environment:                 # option environment see above note
    #  GOTIFY_URLS:          ''
    #  GOTIFY_CLIENT_TOKENS: ''
    #  SECNTFY_TOKENS:       ''
      - TRAEFIK_DASHBOARD_CREDENTIALS:${TRAEFIK_DASHBOARD_CREDENTIALS}
    env_file: .env # use .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.igotify.entrypoints=http"
      - "traefik.http.routers.igotify.rule=Host(`igotify.domain.com`)"
      - "traefik.http.middlewares.igotify-auth.basicauth.users=Hrust:${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.igotify-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.igotify.middlewares=igotify-https-redirect"
      - "traefik.http.routers.igotify-secure.entrypoints=https"
      - "traefik.http.routers.igotify-secure.rule=Host(`igotify.domain.com`)"
      - "traefik.http.routers.igotify-secure.middlewares=igotify-auth"
      - "traefik.http.routers.igotify-secure.tls=true"
      - "traefik.http.routers.igotify-secure.service=igotify"
      - "traefik.http.services.igotify.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```
