### ISSUE TITLE
[BUG] bekomme iGotify nicht zum laufen

### ISSUE THREAD

**Issue by Dirk23** [androidseb25/iGotify-Notification-Assistent#133]
**Describe the bug**
Ich habe iGotify nach dem docker-compose.yml File aufgesetzt, wie es auf der Seite steht. Ich logge mich mit der App ein und lege eine App an, sende dann per curl an den Token eine Testnachricht. Kein Push kommt an meinem iOS Gerät an.

Docker Log sagt:

```
docker compose up -d && docker compose logs -f
[+] Running 1/1
 ✔ igotify Pulled                                                                                                                                                                                                                                                                                                                                                                                                                                0.5s
[+] Running 3/3
 ✔ Network igotify_net  Created                                                                                                                                                                                                                                                                                                                                                                                                                  0.1s
 ✔ Container gotify     Started                                                                                                                                                                                                                                                                                                                                                                                                                  2.3s
 ✔ Container igotify    Started                                                                                                                                                                                                                                                                                                                                                                                                                  2.1s
gotify   | Starting Gotify version 2.6.1@2024-11-16-08:49:43
gotify   | Started listening for plain connection on tcp [::]:80
igotify  | Database is created: True
igotify  | Gotify Url list is: empty
igotify  | Gotify Client list is: empty
igotify  | SecNtfy Token list is: empty
igotify  | If one or more lists are empty please check the environment variable! GOTIFY_SERVERS or GOTIFY_CLIENTS or NTFY_TOKENS
igotify  | If all lists are empty do nothing, you will configure the gotify server over the iGotify app.
igotify  | info: Microsoft.Hosting.Lifetime[14]
igotify  |       Now listening on: http://[::]:8080
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Application started. Press Ctrl+C to shut down.
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Hosting environment: Production
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Content root path: /app
gotify   | 2025-02-20T10:15:52Z | 200 |     136.011µs |     172.29.9.10 | GET      "/version"
igotify  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
igotify  |       Failed to determine the https port for redirect.
gotify   | 2025-02-20T10:16:14Z | 200 |   99.980924ms |     172.29.9.10 | POST     "/client"
gotify   | 2025-02-20T10:16:15Z | 200 |    7.495909ms |     172.29.9.10 | GET      "/current/user"
gotify   | 2025-02-20T10:16:15Z | 200 |     558.846µs |     172.29.9.10 | GET      "/application"
gotify   | 2025-02-20T10:16:15Z | 200 |     891.273µs |     172.29.9.10 | GET      "/message?since=0"
igotify  | ClientToken: geändert-abc123
igotify  | DeviceToken: NTFY-DEVICE-geändert-abc123
igotify  | GotifyUrl: https://notify.geht.euch.nix.an
igotify  | Client connecting...
igotify  | Done!
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
gotify   | 2025-02-20T10:16:25Z | 200 |     420.134µs |     172.29.9.10 | GET      "/application"
gotify   | 2025-02-20T10:16:25Z | 200 |     407.433µs |     172.29.9.10 | GET      "/application"
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
gotify   | 2025-02-20T10:16:32Z | 200 |   10.080118ms |     172.29.9.10 | POST     "/application"
gotify   | 2025-02-20T10:16:33Z | 200 |     467.138µs |     172.29.9.10 | GET      "/application"
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
gotify   | 2025-02-20T10:16:57Z | 200 |  102.654905ms |     172.29.9.10 | POST     "/client"
gotify   | 2025-02-20T10:16:57Z | 200 |     8.27587ms |     172.29.9.10 | GET      "/current/user"
gotify   | 2025-02-20T10:16:57Z | 200 |      498.94µs |     172.29.9.10 | GET      "/stream?token=[masked]"
gotify   | 2025-02-20T10:16:57Z | 200 |     497.241µs |     172.29.9.10 | GET      "/application"
gotify   | 2025-02-20T10:16:57Z | 200 |     450.137µs |     172.29.9.10 | GET      "/message?since=0"
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
gotify   | 2025-02-20T10:16:59Z | 200 |      501.24µs |     172.29.9.10 | GET      "/application"
gotify   | 2025-02-20T10:17:03Z | 200 |     453.837µs |     172.29.9.10 | GET      "/client"
gotify   | 2025-02-20T10:17:03Z | 200 |    8.236966ms |     172.29.9.10 | DELETE   "/client/2"
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
gotify   | 2025-02-20T10:17:15Z | 200 |    16.22241ms |     172.29.9.10 | POST     "/message?token=[masked]"
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
gotify   | 2025-02-20T10:17:17Z | 200 |     453.437µs |     172.29.9.10 | GET      "/application"
gotify   | 2025-02-20T10:17:17Z | 200 |     401.032µs |     172.29.9.10 | GET      "/application"
gotify   | 2025-02-20T10:17:17Z | 200 |     507.141µs |     172.29.9.10 | GET      "/message?since=0"
gotify   | 2025-02-20T10:17:17Z | 200 |     430.935µs |     172.29.9.10 | GET      "/message?since=0"
```

Docker Compose File:

```
services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - net
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    environment:
      GOTIFY_DEFAULTUSER_PASS:  'password'

  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - net
    ports:
      - "8080:8080"
    volumes:
      - ./api-data:/app/data
    #environment:                 # option environment see above note
    # GOTIFY_URLS: 'http://gotify'
    # ENABLE_SCALAR_UI: 'true'
    #  - GOTIFY_CLIENT_TOKENS='CSzDjaYvWePmPTk'
    #  SECNTFY_TOKENS:       ''
networks:
  net:
```

NginX proxy Manager:

Getestet mit und ohne die Einträge in Advanced. In beiden URLs hinterlegt und auch bei jedem einzeln:

<img width="1276" alt="Image" src="https://github.com/user-attachments/assets/199add01-8da3-4d7b-932b-83f97025cb76" />

<img width="504" alt="Image" src="https://github.com/user-attachments/assets/6184589f-a399-42ab-98c5-691742251825" />

**Expected behavior**
1. nach dem Anlegen einer App in der iOS-App sollte man den Token sehen können. Derzeit ist es nötig sich dazu im Web anzumelden um die Token zu erfahren
2. iOS Device sollte einen Push erhalten, das tut es aber nicht. In der Liste der Nachrichten erscheint die Testnachricht erst, nach einem "refresh" (Pull Down)

**Screenshots**
zu 1. 

<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/52ad86c8-549e-4a33-a33a-daa2a30327ea" />

zu 2:

<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/cb731e08-817d-4d83-884d-7b227f8547e7" />

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: iOS18.3.1
 - Version of iGotify: 1.3.1.0
