### ISSUE TITLE
Notice: you need to provide a valid access token

### ISSUE THREAD

**Issue by JdCpuWiz** [androidseb25/iGotify-Notification-Assistent#145]
I have gotify running in docker on and LXC in proxmox.  I have no issues recieving notifications from other applications running in the same environment.  I cannot see to get iGotify to connect 
I have a client set up for my phone as well as a login for the user i am trying to connect with.
I just cannot figure out what I am doing wrong.

excerpt from log file:

```
 ✔ Container gotify   Recreated                                                                                                    0.0s 
 ✔ Container igotify  Recreated                                                                                                    0.0s 
Attaching to gotify, igotify
gotify   | Starting Gotify version 2.6.1@2024-11-16-08:49:43
gotify   | Started listening for plain connection on tcp [::]:80
igotify  | Database is created: True
igotify  | Gotify Url list is: empty
igotify  | Gotify Client list is: empty
igotify  | SecNtfy Token list is: empty
igotify  | If one or more lists are empty please check the environment variable! GOTIFY_SERVERS or GOTIFY_CLIENTS or NTFY_TOKENS
igotify  | If all lists are empty do nothing, you will configure the gotify server over the iGotify app.
igotify  | info: Microsoft.Hosting.Lifetime[14]
igotify  |       Now listening on: http://[::]:8080
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Application started. Press Ctrl+C to shut down.
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Hosting environment: Production
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Content root path: /app
gotify   | 2025-03-22T07:39:54-05:00 | 200 |    2.711048ms |   192.168.7.192 | GET      "/"
gotify   | 2025-03-22T07:39:54-05:00 | 200 |     262.761µs |   192.168.7.192 | GET      "/manifest.json"
gotify   | 2025-03-22T07:39:54-05:00 | 200 |    1.711455ms |   192.168.7.192 | GET      "/current/user"
gotify   | 2025-03-22T07:39:54-05:00 | 200 |    2.246708ms |   192.168.7.192 | GET      "/client"
gotify   | 2025-03-22T07:39:54-05:00 | 200 |     1.94718ms |   192.168.7.192 | GET      "/application"
gotify   | 2025-03-22T07:39:54-05:00 | 200 |    1.571517ms |   192.168.7.192 | GET      "/stream?token=[masked]"
igotify  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
igotify  |       Failed to determine the https port for redirect.
gotify   | 2025-03-22T07:40:31-05:00 | 200 |   35.193427ms |   192.168.7.192 | DELETE   "/client/5"
gotify   | 2025-03-22T07:40:31-05:00 | 200 |    1.118233ms |   192.168.7.192 | GET      "/client"
```
```
Docker compose file:
services:
  gotify:
    image: gotify/server:2.6.1
    container_name: gotify
    ports:
      - 8680:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - GOTIFY_SERVER_PORT=80
      - GOTIFY_SERVER_KEEPALIVEPERIODSECONDS=0
      - GOTIFY_SERVER_LISTENADDR=0.0.0.0
      - GOTIFY_SERVER_STREAM_PINGPERIODSECONDS=45
      - GOTIFY_DATABASE_DIALECT=postgres
      - GOTIFY_DATABASE_CONNECTION=host=192.168.7.223 port=5432 user=gotify dbname=gotify password=gotify
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=admin
      - GOTIFY_PASSSTRENGTH=10
      - GOTIFY_UPLOADEDIMAGESDIR=data/images
      - GOTIFY_PLUGINSDIR=data/plugins
      - GOTIFY_REGISTRATION=false
    volumes:
      - /mypath/gotify/data:/app/data
    restart: unless-stopped
    networks:
      - gotify-private
  
  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=America/Chicago
      - GOTIFY_URLS:'http://gotify:80'
      - GOTIFY_CLIENT_TOKEN:_<REDACTED>_
      - GOTIFY_DEFAULTUSER_PASS=_<REDACTED>_
      - ENABLE_CONSOLE_LOG=true
      - ENABLE_SCALAR_UI=true
    ports:
      - 8681:8080
    volumes:
      - /mypath/gotify/igotify/data:/app/data
    networks:
      - gotify-private

networks:
  gotify-private:
    external: true
```
