### ISSUE TITLE
[BUG] Disconnection happened, type: Error

### ISSUE THREAD

**Issue by AlexandruNegura** [androidseb25/iGotify-Notification-Assistent#146]
**Describe the bug**
Websocket calls from iGotify to the server seem to not work.
In Igotify logs I get: 
```
Gotify - Url: http://192.168.1.182:8680
Is Gotify - Url available: yes
SecNtfy Server - Url: https://api.secntfy.app
Is SecNtfy Server - Url available: yes
Client - Token: <TOKEN_PLACEHOLDER>
Client connecting...
Done!
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
Disconnection happened, type: Error
Webseocket Reconnection failed with Error. Try to reconnect in 10s.
Disconnection happened, type: Error
Webseocket Reconnection failed with Error. Try to reconnect in 10s.
Disconnection happened, type: Error
```

In gotify I get:
```
2025-03-23T16:50:41Z | 401 |      158.78µs |      172.18.0.3 | GET      "/stream?token=[masked]"
Error #01: you need to provide a valid access token or user credentials to access this api
```

**Expected behavior**
No errors were supposed to pop up in both containers's logs
Not sure tho what is not working since alerts do come in. 

**Additional context**
Docker compose file

```
services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "8680:80"
    volumes:
      - data:/app/data
    environment:
      GOTIFY_DEFAULTUSER_PASS:  '<PASSWORD>'   # Change me!!!!!

  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    ports:
      - "8681:8080"
    volumes:
      - api-data:/app/data
    environment:                 # option environment see above note
      GOTIFY_URLS:          'http://192.168.1.182:8680'
      GOTIFY_CLIENT_TOKENS: '<TOKEN>'
      SECNTFY_TOKENS:       '<SEC_TOKEN>'

volumes:
  data:
  api-data:
```
