### ISSUE TITLE
[BUG] Gotify Server is not available

### ISSUE THREAD

**Issue by Teonyr** [androidseb25/iGotify-Notification-Assistent#56]
**Describe the bug**
I've set up Gotify & iGotify according to the docker compose file found in this repository.
Gotify itself is working and I can connect with my phone (through iGotify app) or via webbrowser and I can see Notifications.
However I dont receive push messages on my phone and looking at the log I see the error messages you can read below in "Log".

**Expected behavior**
Everything should work.

**Used Docker Compose**
```
version: "3.8"
services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - backend
    labels:
      traefik.enable: true
      traefik.http.routers.gotify.entrypoints: web, websecure
      traefik.http.routers.gotify.tls: true
      traefik.http.routers.gotify.rule: ( Host(`gotify.REDACTED`) )
      traefik.http.services.gotify.loadbalancer.server.port: 80
    volumes:
      - /persistent/gotify/data:/app/data
    env_file:
      - .env
  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - backend
    volumes:
      - /persistent/gotify/api-data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.igotify.entrypoints: web, websecure
      traefik.http.routers.igotify.tls: true
      traefik.http.routers.igotify.rule: ( Host(`igotify.REDACTED`) )
      traefik.http.services.igotify.loadbalancer.server.port: 8080
networks:
  backend:
    external: true
```
**Contents of .env**
```
TZ=Europe/Berlin
GOTIFY_DEFAULTUSER_PASS=REDACTED
```

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: 17.4.1
 - Version of Container :latest
 - Version of iGotify :latest

**Log**
> 22.04.2024 09:25:09 Database is created: True
> 22.04.2024 09:25:10 Gotify Server is not available try to reconnect in 10s.
> 22.04.2024 09:25:10 info: Microsoft.Hosting.Lifetime[14]
> 22.04.2024 09:25:10       Now listening on: http://[::]:8080
> 22.04.2024 09:25:10 info: Microsoft.Hosting.Lifetime[0]
> 22.04.2024 09:25:10       Application started. Press Ctrl+C to shut down.
> 22.04.2024 09:25:10 info: Microsoft.Hosting.Lifetime[0]
> 22.04.2024 09:25:10       Hosting environment: Production
> 22.04.2024 09:25:10 info: Microsoft.Hosting.Lifetime[0]
> 22.04.2024 09:25:10       Content root path: /app
> 22.04.2024 09:25:20 Reconnecting...
> 22.04.2024 09:25:20 Gotify Server is not available try to reconnect in 10s.
> 22.04.2024 09:25:30 Reconnecting...
> 22.04.2024 09:25:30 Gotify Server is not available try to reconnect in 10s.

**Additional Information**
The app/service I used, to test if gotify itself works, is Jellyseerr. It is deployed by docker compose too, uses also the "backend" network and does connect to gotify via: http://gotify.
![grafik](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/75175693/402c8f1c-731a-46a6-8460-a3777f2e8368)

I would greatly appreciate any help.
If you need more information, I'm happy to deliver them.
