### ISSUE TITLE
[BUG] Can't log in to iGotify App

### ISSUE THREAD

**Issue by Stefan3005** [androidseb25/iGotify-Notification-Assistent#61]
**Describe the bug**
Hello together,

today I tried to set up Gotify with iGotify. But I have an issue when want to login to the iGotify App on my IPhone.
I can open the Gotify and iGotify Site. I can login to Gotify with the (Test) Credentials: "admin" "test1234" and the iGotify APP finds both addresses. But when I type in my credentials, an error message occur (See in the Screenshots (Don't be confused, on the screenshot it looks as if no password has been entered but i entered "test1234"))

Can somebody explain, what I have done wrong?

**Expected behavior**
Login with my credentials to the iGotify App.

**Yaml File**
```yml
# Docker Compose File for uptime gotify + igotify
# Supposed path: /srv/gotify/docker-compose.yml

services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server:latest
    # image: gotify/server-arm7
    # image: gotify/server-arm64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - net
      - default
    #ports:
      #- "8680:80"
    volumes:
      - ./data:/app/data
    environment:
      TZ:                       'Europe/Berlin'
      GOTIFY_DEFAULTUSER_PASS:  'test1234'   # Change me!!!!!

  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - net
      - default
    #ports:
      #- "8681:8080"
    environment:
      - IGOTIFY_CLIENT_TOKEN='CUqwy0kkAZbYxu4'
      - GOTIFY_SERVER_URL="http://gotify"
    volumes:
      - ./api-data:/app/data

networks:
  net:
  default:
    external: true
    name: reverseProxyNetwork

volumes:
  data:
  api-data:
```

**Screenshots**
![Bildschirmfoto 2024-05-18 um 11 13 43](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/63395544/9e0a28f8-8b70-45ae-bac4-eae6495658c5)
![2024-05-18 11_21_19-Window](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/63395544/d2d0d70a-7d36-4ac3-b617-752a82e135ab)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
.. - OS: 17.4.1
 - Version of Container 2.4.0
 - Version of iGotify: 1.2.0.3

**Additional context**
