### ISSUE TITLE
[BUG] Websocket Error iGotify & DNS Spamming

### ISSUE THREAD

**Issue by benniblot** [androidseb25/iGotify-Notification-Assistent#95]
**Describe the bug**
Push-Notifications work fine, but I get the following errors spammed inside my console. On top of that, iGotify spams my DNS Server with requests for the Gotify IP.

Error inside iGotify: 
```
Disconnection happened, type: Error
Webseocket Reconnection failed with Error. Try to reconnect in 10s.
```

Error inside Gotify: 
```
Error #01: you need to provide a valid access token or user credentials to access this api
2024-09-20T21:02:35+02:00 | 401 |     529.109µs |      172.23.0.4 | GET      "/stream?token=[masked]"
```

**Expected behavior**
No error / DNS spamming. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: IOS 18 (17 didn't make a difference)
 - Version of iGotify Container: 1.3.0.0
 - Version of iGotify App: 1.4 (26)

**Additional context**
my compose:

```yml
services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server-arm64:2.5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - internal_communication
    environment:
      - TZ=Europe/Vienna
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTPASS}
    volumes:
      - /media/smalldata/appdata/gotify/server:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.gotify.entrypoints: http
      traefik.http.routers.gotify.rule: Host(`gotify.xxx.com`)
      traefik.http.routers.gotify.middlewares: gotify-https-redirect
      traefik.http.middlewares.gotify-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.gotify-secure.entrypoints: https
      traefik.http.routers.gotify-secure.rule: Host(`gotify.xxx.com`)
      traefik.http.routers.gotify-secure.tls: "true"
      traefik.http.routers.gotify-secure.service: gotify
      traefik.http.services.gotify.loadbalancer.server.port: "80"
      traefik.docker.network: internal_communication
  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - internal_communication
    volumes:
      - /media/smalldata/appdata/gotify/igotify:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.igotify.entrypoints: http
      traefik.http.routers.igotify.rule: Host(`igotify.xxx.com`)
      traefik.http.routers.igotify.middlewares: igotify-https-redirect
      traefik.http.middlewares.igotify-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.igotify-secure.entrypoints: https
      traefik.http.routers.igotify-secure.rule: Host(`igotify.xxx.com`)
      traefik.http.routers.igotify-secure.tls: "true"
      traefik.http.routers.igotify-secure.service: igotify
      traefik.http.services.igotify.loadbalancer.server.port: "8080"
      traefik.docker.network: internal_communication
networks:
  internal_communication:
    external: true
```

*GOTIFY_DEFAULTPASS is set with .env*
